///
/// @Generated by Mockolo
///



import Combine
import EventKit
import Factory
import Foundation


class DefaultsServiceProtocolMock: DefaultsServiceProtocol {
    init() { }
    init(allowedCalendars: [String] = [String](), filterOnePersonMeetings: Bool = false) {
        self.allowedCalendars = allowedCalendars
        self.filterOnePersonMeetings = filterOnePersonMeetings
    }


    private(set) var allowedCalendarsSetCallCount = 0
    var allowedCalendars: [String] = [String]() { didSet { allowedCalendarsSetCallCount += 1 } }

    private(set) var filterOnePersonMeetingsSetCallCount = 0
    var filterOnePersonMeetings: Bool = false { didSet { filterOnePersonMeetingsSetCallCount += 1 } }
}

class EKServiceProtocolMock: EKServiceProtocol {
    init() { }


    var authorizationStatusChanged: AnyPublisher<EKEntityType, Never> { return self.authorizationStatusChangedSubject.eraseToAnyPublisher() }
    private(set) var authorizationStatusChangedSubject = PassthroughSubject<EKEntityType, Never>()

    private(set) var requestAccessCallCount = 0
    var requestAccessHandler: ((EKEntityType) async throws -> ())?
    func requestAccess(to type: EKEntityType) async throws {
        requestAccessCallCount += 1
        if let requestAccessHandler = requestAccessHandler {
            try await requestAccessHandler(type)
        }
        
    }

    private(set) var authorizationStatusCallCount = 0
    var authorizationStatusHandler: ((EKEntityType) -> EKAuthorizationStatus)?
    func authorizationStatus(for type: EKEntityType) -> EKAuthorizationStatus {
        authorizationStatusCallCount += 1
        if let authorizationStatusHandler = authorizationStatusHandler {
            return authorizationStatusHandler(type)
        }
        fatalError("authorizationStatusHandler returns can't have a default value thus its handler must be set")
    }

    private(set) var eventsCallCount = 0
    var eventsHandler: ((NSPredicate) -> [Event])?
    func events(matching predicate: NSPredicate) -> [Event] {
        eventsCallCount += 1
        if let eventsHandler = eventsHandler {
            return eventsHandler(predicate)
        }
        return [Event]()
    }

    private(set) var calendarsCallCount = 0
    var calendarsHandler: ((EKEntityType) -> [EKCalendar])?
    func calendars(for entityType: EKEntityType) -> [EKCalendar] {
        calendarsCallCount += 1
        if let calendarsHandler = calendarsHandler {
            return calendarsHandler(entityType)
        }
        return [EKCalendar]()
    }

    private(set) var predicateForEventsCallCount = 0
    var predicateForEventsHandler: ((Date, Date, [EKCalendar]?) -> NSPredicate)?
    func predicateForEvents(withStart startDate: Date, end endDate: Date, calendars: [EKCalendar]?) -> NSPredicate {
        predicateForEventsCallCount += 1
        if let predicateForEventsHandler = predicateForEventsHandler {
            return predicateForEventsHandler(startDate, endDate, calendars)
        }
        fatalError("predicateForEventsHandler returns can't have a default value thus its handler must be set")
    }

    private(set) var predicateForRemindersCallCount = 0
    var predicateForRemindersHandler: (([EKCalendar]?) -> NSPredicate)?
    func predicateForReminders(calendars: [EKCalendar]?) -> NSPredicate {
        predicateForRemindersCallCount += 1
        if let predicateForRemindersHandler = predicateForRemindersHandler {
            return predicateForRemindersHandler(calendars)
        }
        fatalError("predicateForRemindersHandler returns can't have a default value thus its handler must be set")
    }

    private(set) var remindersCallCount = 0
    var remindersHandler: ((NSPredicate) async -> [Reminder])?
    func reminders(matching predicate: NSPredicate) async -> [Reminder] {
        remindersCallCount += 1
        if let remindersHandler = remindersHandler {
            return await remindersHandler(predicate)
        }
        return [Reminder]()
    }
}

class EventServiceProtocolMock: EventServiceProtocol {
    init() { }


    private(set) var fetchEventsCallCount = 0
    var fetchEventsHandler: (() -> [Event])?
    func fetchEvents() -> [Event] {
        fetchEventsCallCount += 1
        if let fetchEventsHandler = fetchEventsHandler {
            return fetchEventsHandler()
        }
        return [Event]()
    }

    private(set) var fetchRemindersCallCount = 0
    var fetchRemindersHandler: (() async -> [Reminder])?
    func fetchReminders() async -> [Reminder] {
        fetchRemindersCallCount += 1
        if let fetchRemindersHandler = fetchRemindersHandler {
            return await fetchRemindersHandler()
        }
        return [Reminder]()
    }

    var eventsFetched: AnyPublisher<([Event], [Reminder]), Never> { return self.eventsFetchedSubject.eraseToAnyPublisher() }
    private(set) var eventsFetchedSubject = PassthroughSubject<([Event], [Reminder]), Never>()
}

class CalendarServiceProtocolMock: CalendarServiceProtocol {
    init() { }
    init(allowedCalendars: Set<String> = Set<String>()) {
        self.allowedCalendars = allowedCalendars
    }


    private(set) var fetchCalendarsCallCount = 0
    var fetchCalendarsHandler: ((EKEntityType) -> [EKCalendarItem])?
    func fetchCalendars(type: EKEntityType) -> [EKCalendarItem] {
        fetchCalendarsCallCount += 1
        if let fetchCalendarsHandler = fetchCalendarsHandler {
            return fetchCalendarsHandler(type)
        }
        return [EKCalendarItem]()
    }

    private(set) var allowedCalendarsSetCallCount = 0
    var allowedCalendars: Set<String> = Set<String>() { didSet { allowedCalendarsSetCallCount += 1 } }

    var allowedCalendarsPublisher: AnyPublisher<Set<String>, Never> { return self.allowedCalendarsPublisherSubject.eraseToAnyPublisher() }
    private(set) var allowedCalendarsPublisherSubject = PassthroughSubject<Set<String>, Never>()
}



