///
/// @Generated by Mockolo
///



import EventKit


class AuthorizationServiceProtocolMock: AuthorizationServiceProtocol {
    init() { }
    init(authorizationStatusForEvent: EKAuthorizationStatus) {
        self._authorizationStatusForEvent = authorizationStatusForEvent
    }



    private var _authorizationStatusForEvent: EKAuthorizationStatus!
    var authorizationStatusForEvent: EKAuthorizationStatus {
        get { return _authorizationStatusForEvent }
        set { _authorizationStatusForEvent = newValue }
    }

    private(set) var requestAccessToEventsCallCount = 0
    var requestAccessToEventsHandler: (() async throws -> ())?
    func requestAccessToEvents() async throws {
        requestAccessToEventsCallCount += 1
        if let requestAccessToEventsHandler = requestAccessToEventsHandler {
            try await requestAccessToEventsHandler()
        }
        
    }
}



