///
/// @Generated by Mockolo
///



import EventKit


class EventsServiceProtocolMock: EventsServiceProtocol {
    init() { }
    init(authorizationStatusForEvent: EKAuthorizationStatus) {
        self._authorizationStatusForEvent = authorizationStatusForEvent
    }



    private var _authorizationStatusForEvent: EKAuthorizationStatus!
    var authorizationStatusForEvent: EKAuthorizationStatus {
        get { return _authorizationStatusForEvent }
        set { _authorizationStatusForEvent = newValue }
    }

    private(set) var requestAccessToEventsCallCount = 0
    var requestAccessToEventsHandler: (() async throws -> ())?
    func requestAccessToEvents() async throws {
        requestAccessToEventsCallCount += 1
        if let requestAccessToEventsHandler = requestAccessToEventsHandler {
            try await requestAccessToEventsHandler()
        }
        
    }

    private(set) var eventsCallCount = 0
    var eventsHandler: ((NSPredicate) -> [EKEvent])?
    func events(matching predicate: NSPredicate) -> [EKEvent] {
        eventsCallCount += 1
        if let eventsHandler = eventsHandler {
            return eventsHandler(predicate)
        }
        return [EKEvent]()
    }

    private(set) var calendarsCallCount = 0
    var calendarsHandler: ((EKEntityType) -> [EKCalendar])?
    func calendars(for entityType: EKEntityType) -> [EKCalendar] {
        calendarsCallCount += 1
        if let calendarsHandler = calendarsHandler {
            return calendarsHandler(entityType)
        }
        return [EKCalendar]()
    }
}



